spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
  cloud:
    gateway:
      routes:
        - id: payment-service
          uri: ${PAYMENT_SERVICE_URL:http://payment-service:8081}
          predicates:
            - Path=/api/payments/**
        - id: notification-service
          uri: ${NOTIFICATION_SERVICE_URL:http://notification-service:8082}
          predicates:
            - Path=/api/notifications/**
        - id: payment-swagger
          uri: http://payment-service:8081
          predicates:
            - Path=/payment/swagger-ui/**,/payment/api-docs/**,/payment/v3/api-docs/**
          filters:
            - StripPrefix=1
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://localhost:5173"
              - "http://34.246.208.69:8080"
              - "http://34.246.208.69:8081"
              - "http://34.246.208.69"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true

logging:
  level:
    root: WARN
    com.minipay: INFO
    org.springframework.cloud.gateway: DEBUG

springdoc:
  servers:
    - url: http://34.246.208.69:8080
      description: Production server
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: api-gateway
        url: /api-docs
      - name: payment-service
        url: /payment/api-docs