spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/minipay_payments
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop

  kafka:
    bootstrap-servers: localhost:9092

mpesa:
  base-url: https://sandbox.safaricom.co.ke
  callback-url: http://localhost:8081/api/payments/mpesa/callback

logging:
  level:
    com.minipay: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG